# Generated by Django 5.0.4 on 2024-05-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Consumer'), (2, 'Provider')])),
                ('viewer_pass', models.CharField(max_length=128)),
                ('worker_pass', models.CharField(max_length=128)),
                ('manager_pass', models.CharField(max_length=128)),
            ],
        ),
    ]
