# Generated by Django 5.0.4 on 2024-05-04 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_by', to=settings.AUTH_USER_MODEL)),
                ('from_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_from', to=settings.AUTH_USER_MODEL)),
                ('to_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
