# Generated by Django 5.0.4 on 2024-05-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='recieved',
            new_name='received',
        ),
    ]
